# Generated by Django 3.1.5 on 2021-01-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '첫 프로젝트 사용자', 'verbose_name_plural': 'myfirstproject 사용자'},
        ),
    ]
